import { Project, Skill, SocialLink } from './types';
import { 
  GitHubIcon, FacebookIcon, InstagramIcon, TelegramIcon, 
  PhoneIcon, WhatsAppIcon, MailIcon 
} from './components/Icons';

export const SOCIAL_LINKS: SocialLink[] = [
  { name: 'Phone', url: 'tel:+201141345223', icon: PhoneIcon, label: 'Call Me' },
  { name: 'WhatsApp', url: 'https://wa.me/201141345223', icon: WhatsAppIcon, label: 'Chat on WhatsApp' },
  { name: 'Email', url: 'mailto:ayrn194@gmail.com', icon: MailIcon, label: 'Send Email' },
  { name: 'GitHub', url: 'https://github.com/kl0l69', icon: GitHubIcon, label: 'View GitHub Profile' },
  { name: 'Facebook', url: 'https://facebook.com/nq703', icon: FacebookIcon, label: 'Connect on Facebook' },
  { name: 'Instagram', url: 'https://instagram.com/kl0l69', icon: InstagramIcon, label: 'Follow on Instagram' },
  { name: 'Telegram', url: 'https://t.me/nq703', icon: TelegramIcon, label: 'Message on Telegram' },
];

export const SKILLS: Skill[] = [
  // Programming & Web Development
  { name: 'React', category: 'Programming & Web Development' },
  { name: 'TypeScript', category: 'Programming & Web Development' },
  { name: 'Python', category: 'Programming & Web Development' },
  { name: 'C / C++', category: 'Programming & Web Development' },
  { name: 'SQL / MongoDB', category: 'Programming & Web Development' },
  { name: 'HTML / CSS', category: 'Programming & Web Development' },
  { name: 'Web Development', category: 'Programming & Web Development' },
  { name: 'Tailwind CSS', category: 'Programming & Web Development' },

  // Interactive & Animations
  { name: 'GSAP', category: 'Interactive & Animations' },
  { name: 'Three.js / React Three Fiber', category: 'Interactive & Animations' },
  { name: '3D & CSS Animations', category: 'Interactive & Animations' },
  { name: 'Animated Interactive UI', category: 'Interactive & Animations' },

  // AI & Automation
  { name: 'AI Bots / Assistants', category: 'AI & Automation' },
  { name: 'Vosk STT (Offline)', category: 'AI & Automation' },
  { name: 'Prompt Engineering', category: 'AI & Automation' },
  { name: 'Gemini', category: 'AI & Automation' },
  { name: 'GPT Models', category: 'AI & Automation' },
  { name: 'Copilot / Dev0', category: 'AI & Automation' },
  { name: 'AI Tools / APIs', category: 'AI & Automation' },

  // Cybersecurity & OSINT
  { name: 'OSINT Tools Dev', category: 'Cybersecurity & OSINT' },
  { name: 'Cyber Tools & Recon', category: 'Cybersecurity & OSINT' },
  { name: 'Lab Setup', category: 'Cybersecurity & OSINT' },

  // Design & Branding
  { name: 'UI / UX Design', category: 'Design & Branding' },
  { name: 'Branding & Identity', category: 'Design & Branding' },
  { name: 'Graphic Design', category: 'Design & Branding' },
  { name: 'Motion Graphics', category: 'Design & Branding' },

  // Tools & Workflow
  { name: 'Git / GitHub', category: 'Tools & Workflow' },
  { name: 'VS Code', category: 'Tools & Workflow' },
  { name: 'Linux Basics', category: 'Tools & Workflow' },
  { name: 'Project Management', category: 'Tools & Workflow' },
];

export const PROJECTS: Project[] = [
  {
    id: 1,
    name: 'love-u',
    description: 'تطبيق ويب تفاعلي رومانسي وخفيف تم تصميمه لمفاجأة شخص تحبه بطريقة لذيذة. يحتوي على أنيميشن لطيفة، أصوات مرحة، وتفاعلات ممتعة تضيف لمسة لطيفة للتجربة.',
    language: 'TypeScript',
    languageColor: '#3178c6',
    stars: 124,
    forks: 32,
    repoUrl: 'https://github.com/kl0l69/love-u',
    demoUrl: '#',
  },
  {
    id: 2,
    name: 'luxury-events',
    description: 'منصة إلكترونية مخصصة لإدارة وتنظيم الفعاليات الفاخرة في مصر. توفر تجربة مستخدم راقية مع واجهة منظمة لخدمات المناسبات.',
    language: 'React',
    languageColor: '#61dafb',
    stars: 89,
    forks: 15,
    repoUrl: 'https://github.com/kl0l69/luxury-events',
  },
  {
    id: 3,
    name: 'Voice-Control-Assistant',
    description: 'مساعد صوتي ذكي يعمل بالأوامر الصوتية. يستمع لأوامر المستخدم وينفّذها فورًا باستخدام معالجة صوتية تعمل بدون إنترنت (Offline).',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 210,
    forks: 45,
    repoUrl: 'https://github.com/kl0l69/Voice-Control-Assistant',
  },
  {
    id: 4,
    name: 'loly-app',
    description: 'تصميم وتطوير تطبيق لعرض محتوى مرئي وشخصيات، مع تجربة استخدام بسيطة وسلسة.',
    language: 'Dart',
    languageColor: '#00B4AB',
    stars: 56,
    forks: 8,
    isPrivate: true,
    repoUrl: '#',
  },
  {
    id: 5,
    name: 'Amara',
    description: 'نظام ويب احترافي لإدارة واجهة تطبيق متكامل مع تصميم انسيابي وتجربة استخدام واضحة.',
    language: 'Vue',
    languageColor: '#41b883',
    stars: 42,
    forks: 4,
    isPrivate: true,
    repoUrl: '#',
  },
  {
    id: 6,
    name: 'Portfolio-1',
    description: 'موقع بورتفوليو تفاعلي بواجهة حديثة ورسوميات ثلاثية الأبعاد وخلفيات متحركة، يعرض أعمال مطور واجهات بطريقة احترافية.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 180,
    forks: 35,
    repoUrl: 'https://github.com/kl0l69/Portfolio-1',
  },
  {
    id: 7,
    name: 'Rakan-To-Do',
    description: 'تطبيق ويب لإدارة المهام اليومية بسهولة وسرعة، مع واجهة عصرية وخيارات للتحكم الكامل في المهام.',
    language: 'React',
    languageColor: '#61dafb',
    stars: 65,
    forks: 12,
    repoUrl: 'https://github.com/kl0l69/Rakan-To-Do',
  },
  {
    id: 8,
    name: 'rob3-mashwy',
    description: 'موقع ويب عصري بصفحات ديناميكية، وهيكلة نظيفة، وتصميم مرن مع قابلية للتوسع.',
    language: 'HTML',
    languageColor: '#e34c26',
    stars: 30,
    forks: 5,
    repoUrl: 'https://github.com/kl0l69/rob3-mashwy',
  },
  {
    id: 9,
    name: 'anaconda-cyber',
    description: 'دليل تفاعلي شامل لأدوات الأمن السيبراني، يحتوي على شروحات منظمة، Playbooks، وتجهيز مختبرات الاختبار.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 450,
    forks: 120,
    repoUrl: 'https://github.com/kl0l69/anaconda-cyber',
  },
  {
    id: 10,
    name: 'kl0l69',
    description: 'مستودع عام يحتوي على أكواد وتجارب متنوعة خاصة بالمطور.',
    language: 'Markdown',
    languageColor: '#083fa1',
    stars: 1500,
    forks: 80,
    repoUrl: 'https://github.com/kl0l69/kl0l69',
  },
  {
    id: 11,
    name: 'portfolio',
    description: 'بورتفوليو شخصي مستوحى من طابع سينمائي مع لمسات مصرية، يعرض المهارات والأعمال بطريقة جذابة.',
    language: 'TypeScript',
    languageColor: '#3178c6',
    stars: 90,
    forks: 15,
    repoUrl: 'https://github.com/kl0l69/portfolio',
  },
  {
    id: 12,
    name: 'cpp-reviewer',
    description: 'منصة لشرح ومراجعة لغة C++ بشكل تفاعلي وسهل، تحتوي على موضوعات منظمة وتمارين.',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 200,
    forks: 45,
    repoUrl: 'https://github.com/kl0l69/cpp-reviewer',
  },
  {
    id: 13,
    name: 'Lisker',
    description: 'تطبيق ويب لإدارة الروابط بسرعة وتنظيم، مع واجهة بسيطة وتحكم كامل في الروابط.',
    language: 'Next.js',
    languageColor: '#000000',
    stars: 55,
    forks: 8,
    repoUrl: 'https://github.com/kl0l69/Lisker',
  },
  {
    id: 14,
    name: 'loly-README',
    description: 'صفحة تعريف لأداة "Loly" مع عرض خصائص ومميزات الأداة بطريقة منظمة.',
    language: 'Markdown',
    languageColor: '#083fa1',
    stars: 25,
    forks: 3,
    repoUrl: 'https://github.com/kl0l69/loly-README',
  },
  {
    id: 15,
    name: 'E-V-O',
    description: 'نظام إدارة براند بشكل متكامل، يعرض المهام والإدارة الداخلية بشكل مرتب.',
    language: 'PHP',
    languageColor: '#4F5D95',
    stars: 40,
    forks: 6,
    repoUrl: 'https://github.com/kl0l69/E-V-O',
  },
  {
    id: 16,
    name: 'OSINT',
    description: 'موقع يحتوي على أدوات تحليل معلومات وروابط—مفيد للباحثين في مجال الاستخبارات مفتوحة المصدر.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 600,
    forks: 150,
    repoUrl: 'https://github.com/kl0l69/OSINT',
  },
  {
    id: 17,
    name: 'assignment',
    description: 'صفحة عرض لحل أسايمنت خاص بالجامعة.',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 10,
    forks: 2,
    repoUrl: 'https://github.com/kl0l69/assignment',
  },
  {
    id: 18,
    name: 'AZ',
    description: 'موقع لعرض مشروع تيم جامعي بطريقة منظمة واحترافية.',
    language: 'HTML',
    languageColor: '#e34c26',
    stars: 18,
    forks: 4,
    repoUrl: 'https://github.com/kl0l69/AZ',
  },
  {
    id: 19,
    name: 'ARSINEK-BOT',
    description: 'بوت واتساب متكامل لإدارة المحادثات ومربوط بالذكاء الاصطناعي لتنفيذ أوامر وتحسين التفاعل.',
    language: 'JavaScript',
    languageColor: '#f1e05a',
    stars: 135,
    forks: 28,
    repoUrl: 'https://github.com/kl0l69/ARSINEK-BOT',
  },
  {
    id: 20,
    name: 'tele-1.bot',
    description: 'بوت تيليجرام لإدارة مهام وتنظيم عمليات داخل مجموعات أو قنوات.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 145,
    forks: 30,
    repoUrl: 'https://github.com/kl0l69/tele-1.bot',
  },
  {
    id: 21,
    name: 'arsinek-portfolio',
    description: 'نسخة من بورتفوليو مبكر يعرض أعمالك ومعلوماتك الأساسية.',
    language: 'TypeScript',
    languageColor: '#3178c6',
    stars: 60,
    forks: 8,
    repoUrl: 'https://github.com/kl0l69/arsinek-portfolio',
  },
  {
    id: 22,
    name: 'follow.sc',
    description: 'بوت لزيادة المتابعين مع واجهة استخدام بسيطة وسهلة.',
    language: 'Node.js',
    languageColor: '#339933',
    stars: 220,
    forks: 55,
    repoUrl: 'https://github.com/kl0l69/follow.sc',
  },
  {
    id: 23,
    name: 'esraa-hussien.io',
    description: 'موقع بورتفوليو لمعالجة نفسية، بتصميم هادي واحترافي يعرض الخدمات والمعلومات.',
    language: 'Vue',
    languageColor: '#41b883',
    stars: 80,
    forks: 14,
    repoUrl: 'https://github.com/kl0l69/esraa-hussien.io',
  },
];
